deno run -A main.ts "A demolition aimed at the heart of domesticated rationality.
There is a deception at the core of our culture: that we are the architects of our being. But this is a lie, and not out of pessimism, or nihilism, or cynicism, but out of truthfulness: what one is, is not chosen; it is recognized within you.
Deleuze, Damasio, Goffman, Pascal, Wittgenstein, Kierkegaard, Heidegger, Panksepp, Barrett, Libet, Gazzaniga, Eagleman, Varela (neurophenomenology). Claude Steele's 'Stereotype Threat'. Zimbardo's Stanford Prison Experiment. Behavioral Priming Studies. Cognitive Dissonance Theory (Festinger). Self-Determination Theory. Narrative Identity (McAdams). Damage to DMN regions can cause loss of autobiographical coherence, leading to disoriented behavior. Sartre's existentialism: Action defines identity, but identity also informs the scope of action. Foucault: Identity is shaped by power-knowledge systems; your 'self' is a product of historically contingent norms, not pure inner truth.
If identity drives your actions, but your actions shape your identity, isn't this relationship self-referential? A core structural feature of consciousness.
Watch your thoughts, for they become words; watch your words, for they become actions; watch your actions, for they become habits; watch your habits, for they become character; watch your character, for it becomes your destiny. -Frank Outlaw?
It would be a lie to say that identity is the sole driver of your actions, as it does scope a frame for you to follow, and if followed, that will 'shape' your reality.
So identity, more than a driver, is a steering wheel, as the driver is the eyes of the observer behind it, and the place you are in, is a temporary secondary effect of where you were before, and where you are going. There is no driver, there's something driven down the road, but actions don't stop when I stop having an identity, or when I stop attaching the mind to the remote. The TV keeps playing even if you go away, if the TV is on.
It would be a lie if I said that, without identity, there is no driver. It's true that identity drives, but emotions can drive as well. Thoughts can betray you, emotions can betray your thoughts, but emotions, pre-egotistical ones, cannot betray you; post-egotistical ones can. What they show it's sincere; they might not reflect reality, but reality is non-fundamental, reality is the shadow projection of a snapshot that's gone. A moment in time? Time is non-fundamental; time is the rate of change that dilates the more local interactions there are to compute. Emotions reflect something fundamental though… what you truly value, before you being verbal, before the adult, before its narcissism, before its anxious compensating inferiority complex… coping with a reinterpretation of reality where you were not a piece of shit; before the trauma; what you truly value are the deepest parts, unexpectedly pretty, beyond the abyss.
You can call yourself a shapeshifter, you can call yourself a reality bender, but neither your shape shifts, nor your reality changes. You hide your wholeness, then reveal a side. Reality is not shaped by your actions; your actions reveal what was always there, a reality waiting.
Some of you might have already reached the point of changing willingly, knowingly, consciously your identities, subjective assessments, out of the fabrication of your imagination of what this world's version of value is, based on the whereabouts of your reasoning; a non-fundamental artifact of an emergent phenomenon.
Reasoning will not lead us to our subjective truths, but can deconstruct our lies.
Reasoning, counterintuitively, will not lead you to the truth (the subjective one), as reasoning is objective, but your values, the truest, deepest ones beyond the abyss, these are not subject to objectivity.
It's ironic that through reasoning, you find yourself stepping out of it. There is an alternative path, but reasoning and I can only lead you to the door, and after that, everything will turn pre-verbal, pre-conceptual, and I hold no answer (the paradox is that I use reason to bring us to the threshold of what cannot be reasoned: a meta-rationality).
Don't be afraid of the abyss; we are way past that. Beyond that door, you will have to use another language, one without words but way more expressive. Here, lies are prohibited; if you stick to your lies, you will never come back.
Rationality stops at the edge. Here, only the ones who can bear to die.
It's true that identity can change your life, but, against everything the world has taught, you should not choose how to change your life; that decision is not up to them voices, nor up to reasoning, nor up to you. Hear me when I say: that decision is up to your values, and are your values up to you? No. If they were… people with everything in life, with plans, and dreams, and goals, and trophies to shovel off of people's asses, or so said, would not feel dead inside, but they do.
Are you afraid that what you truly value might lead you to destruction? Afraid of friction against convention? But convention is the choice of the many, and the many do not hold the truth, 'heteronomy of the will', the many do not hold the truth.
If you are going to jump off a bridge because of Law and Order, and Jean Valjean is fair and square, and righteousness is a wicked one, then, instead of jumping and ending your life, Javert, embrace the change. Beyond the kid who was beaten up by his father because he was not the perfect child, because father tells himself that his wife left him because he was an imperfect man, lies a kid who just wanted to be embraced, whilst being an imperfect one.
Thoughts reflect words, but not all words reflect thoughts; emotions reflect thoughts, but not all thoughts reflect emotions.
But God!! You might plead atheistically, my emotions are distortions of reactions to what has happened. God!! I'm a narcissist as a coping mechanism for what's never happened.
My son. Beneath that narcissism lies an inferiority complex. Beneath the inferiority complex lies trauma. Beneath that lies something pre-social, pre-verbal, pre-infant, pre-you, pre; a naked animal with its own uncoerced behaviors, with a brain that asses nothing but reactions. Not from trauma, but before it.
That animal has taste, it likes and likes not, and what it likes it values, and that animal is you. So get this. You don't choose your values, your values choose you.
We do what moves us before we know what we are.
What difference is there, then, between action and automatism? There isn't one; all actions are automatic in the resonant response. And you might ask, if all actions are automatic, who acts then? Wrong question. The fact that if you delete the concept of entity doesn't stop the action or the experience shows that the concept of entity is not a fundamental property of reality, but is an artifact of the search for answers. Individuals in liminal states (flow, trance) describe a temporary loss of self, while still performing, meaning that regardless of being, there is an action and an experience.
Choice doesn't exist, but a compulsive search for homeostasis. What you are reading right now is a shortcut. This is not about saving you. This is about letting go of the one hidden behind you. The one you possessed.
You, in that sense, are no different from the roots of a tree looking for water, or the mycelium of a fungus, expanding in the soil in the hopes of living a little longer, a gambler who rest assured, tells Machiavelli to go fuck himself, because, means to an end, when the end gets you, you will never see it, and know that the means were the only thing you had, for you and every other living being is a gambler for the means.
Take the animal for a ride, and where the dog barks, steer towards, and if you are not the driver, jump out the window. Freedom is a post-hoc narrative of what the body has already chosen, seven seconds prior.
What is the ontological status of an act if it isn't framed within a minimum of intention? At the most fundamental level, there is no intention, but the act. By who? By us. What are we? Distractions.
One does not choose what one is, but resonates with what one already was.
So you don't get to choose what's important to you; you find out.
What prevents us from recognizing a conditioned reflex as 'authentic'? If everything is pre-verbal, how do we avoid self-deception?
That would be reasoning the pre-cognitive. That's not reasoned, it's known… instinctively.
Where does that instinct emerge from?
By asking that, you're already trying to fit it into a causal chain, but just as you can't decide to be born, you don't have agency over your intrinsic values ​​either. It's a search in circles.
You don't choose what you want; what you want chooses you.
So (respectfully), fuck what's right. Respectfully, fuck you. What is right for you, you don't get to choose, that choice has already been taken for you, by you, not you, yes you, what the fuck!? And without your consent.
What's the truth? Drive, thrive. Life. What gets you up on Monday morning, never mourning, always thanking for being alive.
If values ​​can't be chosen, then freedom isn't created, but recognized. How can we reconcile that with agency? There is no such need, as there is no such thing; free will has always been a virtuality, and this is where it vanishes (functionality).
Live, says death. If you were going to kill yourself, then live like you are saying goodbye. If you are suicidal, then live and leave no apologies.
That's your identity uncoerced, now coerce it, now frame it, but frame not too tight, for words hold meaning but never encapsulate it right.
Do you understand?
Don't live in reasoning, reason not living in resonance, let resonance experience itself, and reason as an artifact."
