deno run -A main.ts "A demolition aimed at the heart of domesticated rationality.
I will change your life.
There is a deception at the core of our culture: that we are the architects of our being. But this is a lie, and not out of pessimism, but out of truthfulness: what one is, is not chosen; it is recognized within you.
Deleuze, Damasio, Goffman, Pascal, Wittgenstein, Kierkegaard, Panksepp, Barrett, Libet, Gazzaniga, Eagleman, Varela (neurophenomenology). Claude Steele's Stereotype Threat. Zimbardo's Stanford Prison Experiment. Behavioral Priming Studies. Cognitive Dissonance Theory (Festinger). Self-Determination Theory. Narrative Identity (McAdams). Damage to DMN regions can cause loss of autobiographical coherence, leading to disoriented behavior. Sartre's existentialism says that Action defines identity, but identity also informs the scope of action. Foucault shows that Identity is shaped by power-knowledge systems; your self is a product of historically contingent norms, not pure inner truth.
If identity drives your actions, but your actions shape your identity, isn't this relationship self-referential? A core structural feature of consciousness.
Watch your thoughts, for they become words; Watch your words, for they become actions; Watch your actions, for they become habits; Watch your habits, for they become character; Watch your character, for it becomes your destiny. -Frank Outlaw?
It would be a lie to say that identity is the sole driver of your actions, as it does scope a frame for you to follow, and if followed, that will shape your reality.
So identity, more than a driver, is a steering wheel, as the driver is the eyes of the observer behind it, and the place you are in is a temporary secondary effect of where you were before, and where you are going.
There is no driver, there's something driven down the road, but actions don't stop when I stop having an identity, or when I stop attaching the mind to the remote. The TV keeps playing even if you go away, if it's on.
It would be a lie if I said that, without identity, there is no driver. It's true that identity drives, but emotions are driving. Thoughts can betray you, emotions can betray your thoughts, but pre-egotistical emotions cannot betray you (post-egotistical can). It's sincere what they show, they might not reflect reality, but reality is non-fundamental, reality is the shadow projection of a snapshot that's gone.
Time is non-fundamental; time is the rate of change that dilates the more local interactions there are to compute.
Emotions reflect something fundamental… what you truly value, before you being verbal, before the adult, before its narcissism, before its anxious compensating inferiority complex… coping with a reinterpretation of reality where you were not a piece of shit; before the trauma.
These are the deepest parts, unexpectedly pretty, beyond the abyss.
You can call yourself a shapeshifter, you can call yourself a reality bender, but neither your shape shifts, nor your reality changes. You hide your wholeness, then reveal a side. Reality is not shaped by your actions; your actions reveal what was always there.
Some of you might have already reached the point of changing willingly, knowingly, consciously your identities, subjective assessments out of the fabrication of your imagination of what this world's version of value, based on the whereabouts of your reasoning.
Non-fundamental artifact of an emergent phenomenon. Reasoning will not lead us to our subjective truths, but can deconstruct our lies.
Reasoning, counterintuitively, will not lead you to the truth (subjective truth), as reasoning is objective, but your values, the truest, deepest ones beyond the abyss, are not subject to objectivity.
It's ironic that through reasoning, you find yourself stepping out of it. There is an alternative path, but reasoning and I can only lead you to the door, and after that everything will turn preverbal, preconceptual, and I hold no answer (the paradox is that I use reason to bring us to the threshold of what cannot be reasoned: a meta-rationality).
Don't be afraid of the abyss; we are way beyond that. Beyond that door, you will have to use another language, one without words but way more expressive. Here, lies are prohibited; if you lie once, you will never come back. Here, only the ones who can bear to die.
It's true that identity can change your life, but, against everything the world has taught, you should not choose how to change your life; that decision is not up to them voices, nor up to reasoning, nor up to you. Hear me when I say: that decision is up to your values, and your values are not up to you, if they were, people with everything in life, or so said, would not feel dead inside, but they do.
Are you afraid of what you truly value? Afraid of destruction? Afraid of friction against convention? But convention is the choice of the many, and the many do not hold the truth, 'heteronomy of the will', the many do not hold the truth.
Thoughts reflect words, but not all words reflect thoughts; emotions reflect thoughts, but not all thoughts reflect emotions.
But Godcd Obsidian/Oriens\ Omni You might plead atheistically, my emotions are distortions of reactions to what has really happened. Godcd Obsidian/Oriens\ Omni I'm a narcissist as a coping mechanism for what's never happened.
My son. Beneath that narcissism lies an inferiority complex. Beneath the inferiority complex lies trauma. Beneath that lies something pre-social, pre-verbal, pre-infancy, pre-you; a naked animal with its own uncoerced behaviors, with a brain that asses nothing but reactions. Not from trauma, but before it.
That animal has taste, it likes and likes not, and what it likes it values, and that animal is you. So get this. You don't choose your values, your values choose you.
We do what moves us before we know what we are.
What difference is there, then, between action and automatism? There isn't one; all actions always were automatic.
Take the animal for a ride, and where the dog barks, steer towards, and if you are not the driver, jump out the window. Freedom is a post-hoc narrative of what the body has already chosen, seven seconds prior.
What is the ontological status of an act if it isn't framed within a minimum of intention? At the most fundamental level, there is no intention, but the act. By who? By us. What are we? Distractions.
One does not choose what one is, but resonates with what one already is.
So. Respectfully, fuck what's right. Respectfully, fuck you. What is right for you, you don't get to choose, that choice has already been taken for you, by you, not you, yes you, what the fuckWhat's the truth? Drive, thrive, life, what gets you up on Monday morning, never mourning, always thanking for being alive.
If values ​​can't be chosen, then freedom isn't created, but recognized. How can we reconcile that with agency? There is no such need, as there is no such thing; free will has always been a virtuality, and this is where it vanishes (functionality).
Live, says death. If you were gonna kill yourself, then live before it. If you are suicidal, then live and leave nothing.
That's your identity uncoerced, now coerce it, now frame it, but frame not too tight, for words hold meaning but never encapsulate it right.
Don't live in reasoning, live in resonance."
